export const top10Movies = [
    {
        "#TITLE": "The Shawshank Redemption",
        "#YEAR": 1994,
        "#IMDB_ID": "tt0111161",
        "#RANK": 1,
        "#ACTORS": "Tim Robbins, Morgan Freeman",
        "#AKA": "The Shawshank Redemption",
        "#IMDB_URL": "https://www.imdb.com/title/tt0111161",
        "#IMDB_IV": "https://www.imdb.com/title/tt0111161",
        "#IMG_POSTER": "https://m.media-amazon.com/images/I/51NiGlapXlL._AC_.jpg",
        "photo_width": 1000,
        "photo_height": 1500
    },
    {
        "#TITLE": "The Godfather",
        "#YEAR": 1972,
        "#IMDB_ID": "tt0068646",
        "#RANK": 2,
        "#ACTORS": "Marlon Brando, Al Pacino",
        "#AKA": "The Godfather",
        "#IMDB_URL": "https://www.imdb.com/title/tt0068646",
        "#IMDB_IV": "https://www.imdb.com/title/tt0068646",
        "#IMG_POSTER": "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
        "photo_width": 679,
        "photo_height": 1000
    },
    {
        "#TITLE": "The Dark Knight",
        "#YEAR": 2008,
        "#IMDB_ID": "tt0468569",
        "#RANK": 3,
        "#ACTORS": "Christian Bale, Heath Ledger",
        "#AKA": "The Dark Knight",
        "#IMDB_URL": "https://www.imdb.com/title/tt0468569",
        "#IMDB_IV": "https://www.imdb.com/title/tt0468569",
        "#IMG_POSTER": "https://m.media-amazon.com/images/I/81AJdOIEIhL._AC_SY741_.jpg",
        "photo_width": 741,
        "photo_height": 1080
    },
    {
        "#TITLE": "Schindler's List",
        "#YEAR": 1993,
        "#IMDB_ID": "tt0108052",
        "#RANK": 4,
        "#ACTORS": "Liam Neeson, Ralph Fiennes",
        "#AKA": "Schindler's List",
        "#IMDB_URL": "https://www.imdb.com/title/tt0108052",
        "#IMDB_IV": "https://www.imdb.com/title/tt0108052",
        "#IMG_POSTER": "https://m.media-amazon.com/images/M/MV5BMTg3MDc4ODgyOF5BMl5BanBnXkFtZTgwNzY1ODIyNjM@._V1_.jpg",
        "photo_width": 500,
        "photo_height": 740
    },
    {
        "#TITLE": "Pulp Fiction",
        "#YEAR": 1994,
        "#IMDB_ID": "tt0110912",
        "#RANK": 5,
        "#ACTORS": "John Travolta, Uma Thurman",
        "#AKA": "Pulp Fiction",
        "#IMDB_URL": "https://www.imdb.com/title/tt0110912",
        "#IMDB_IV": "https://www.imdb.com/title/tt0110912",
        "#IMG_POSTER": "https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
        "photo_width": 679,
        "photo_height": 1000
    },
    {
        "#TITLE": "The Lord of the Rings: The Return of the King",
        "#YEAR": 2003,
        "#IMDB_ID": "tt0167260",
        "#RANK": 6,
        "#ACTORS": "Elijah Wood, Viggo Mortensen",
        "#AKA": "The Return of the King",
        "#IMDB_URL": "https://www.imdb.com/title/tt0167260",
        "#IMDB_IV": "https://www.imdb.com/title/tt0167260",
        "#IMG_POSTER": "https://m.media-amazon.com/images/I/51Qvs9i5a%2BL._AC_.jpg",
        "photo_width": 500,
        "photo_height": 740
    },
    {
        "#TITLE": "Fight Club",
        "#YEAR": 1999,
        "#IMDB_ID": "tt0137523",
        "#RANK": 7,
        "#ACTORS": "Brad Pitt, Edward Norton",
        "#AKA": "Fight Club",
        "#IMDB_URL": "https://www.imdb.com/title/tt0137523",
        "#IMDB_IV": "https://www.imdb.com/title/tt0137523",
        "#IMG_POSTER": "https://m.media-amazon.com/images/I/51v5ZpFyaFL._AC_.jpg",
        "photo_width": 500,
        "photo_height": 750
    },
    {
        "#TITLE": "Forrest Gump",
        "#YEAR": 1994,
        "#IMDB_ID": "tt0109830",
        "#RANK": 8,
        "#ACTORS": "Tom Hanks, Robin Wright",
        "#AKA": "Forrest Gump",
        "#IMDB_URL": "https://www.imdb.com/title/tt0109830",
        "#IMDB_IV": "https://www.imdb.com/title/tt0109830",
        "#IMG_POSTER": "https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
        "photo_width": 741,
        "photo_height": 1080
    },
    {
        "#TITLE": "Inception",
        "#YEAR": 2010,
        "#IMDB_ID": "tt1375666",
        "#RANK": 9,
        "#ACTORS": "Leonardo DiCaprio, Joseph Gordon-Levitt",
        "#AKA": "Inception",
        "#IMDB_URL": "https://www.imdb.com/title/tt1375666",
        "#IMDB_IV": "https://www.imdb.com/title/tt1375666",
        "#IMG_POSTER": "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg",
        "photo_width": 679,
        "photo_height": 1000
    },
    {
        "#TITLE": "The Matrix",
        "#YEAR": 1999,
        "#IMDB_ID": "tt0133093",
        "#RANK": 10,
        "#ACTORS": "Keanu Reeves, Laurence Fishburne",
        "#AKA": "The Matrix",
        "#IMDB_URL": "https://www.imdb.com/title/tt0133093",
        "#IMDB_IV": "https://www.imdb.com/title/tt0133093",
        "#IMG_POSTER": "https://m.media-amazon.com/images/I/51EG732BV3L._AC_SY679_.jpg",
        "photo_width": 679,
        "photo_height": 1000
    }
]
